### PR TITLE
SFO-4 Added user controller and login controller test cases

### LINKED ISSUE #43: Login Problem
I'm testing and can't log in. But I don't know if I'm doing the right thing. as I read. I must first go to 

`auth/login `

with these parameters 

```
{
  "client_id": "webapp",
  "client_secret": "saqw21!@",
  "username": "super_admin",
  "password": "test123!@#"
}
```

 and that returns this code to me. 

{
  "code": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6IndlYmFwcCIsInVzZXJJZCI6MSwiaWF0IjoxNTg2OTU3MzMzLCJleHAiOjE1ODY5NTc1MTMsImF1ZCI6IndlYmFwcCIsImlzcyI6Im1mZ3FmIiwic3ViIjoic3VwZXJfYWRtaW4ifQ.wgHgBirDz1T9YW1pG133XGBwJRM7q61GsgfCRrpC4ws"
}

Then I must go to 

`auth/token` 

with these parameters 

```
{
  "code": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6IndlYmFwcCIsInVzZXJJZCI6MSwiaWF0IjoxNTg2OTU3MzMzLCJleHAiOjE1ODY5NTc1MTMsImF1ZCI6IndlYmFwcCIsImlzcyI6Im1mZ3FmIiwic3ViIjoic3VwZXJfYWRtaW4ifQ.wgHgBirDz1T9YW1pG133XGBwJRM7q61GsgfCRrpC4ws",
  "clientId": "webapp",
  "username": "super_admin"
}
```

so that it gives me the true token but it returns a 401.

```
{
  "error": {
    "statusCode": 401,
    "name": "UnauthorizedError",
    "message": "Invalid Credentials"
  }
}

```
Can someone tell me what I'm doing wrong?
thank in advance @samarpanB

### PR DESCRIPTION
**Pull request by IshuSF**
## Description

- Added Unit test cases for the User Controller and Login Controller.
- Added **create** function in user_tenant repository to fix the bug where a newly created user tries to get its bearer token using auth/token API. Previously there was no user_tenant record found in the database corresponding to a user record in the createJWT function.

Fixes #43 , #42 , #36 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested ?

- [x] Using the npm test, I verified that all the test cases are successful.
- [x] Successfully got the Bearer token of a newly created user.

## Checklist :

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated

### CODE REVIEW

File: src/repositories/user-tenant.repository.ts [hunk 1]
```diff
@@ -47,4 +50,26 @@ export class UserTenantRepository extends DefaultSoftCrudRepository<
...
+    userTenant.tenantId = user.defaultTenant;
+    const role = await this.roleRepo.findOne({
+      where: {
+        name: process.env.DEFAULT_ROLE,
+      },
+    });
+    if (role && role.id) {
+      userTenant.roleId = role.id;
+    } else {
+      throw new HttpErrors.InternalServerError('Failed to set default role.');
```
Comment (samarpan-b) [inline src/repositories/user-tenant.repository.ts:71]: this should 422 UnprocessableEntity
